// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: protos/twopc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid   string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TwoPCRequest) Reset() {
	*x = TwoPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_twopc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCRequest) ProtoMessage() {}

func (x *TwoPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_twopc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCRequest.ProtoReflect.Descriptor instead.
func (*TwoPCRequest) Descriptor() ([]byte, []int) {
	return file_protos_twopc_proto_rawDescGZIP(), []int{0}
}

func (x *TwoPCRequest) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *TwoPCRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTwoPCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lease int64 `protobuf:"varint,1,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *CreateTwoPCReply) Reset() {
	*x = CreateTwoPCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_twopc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTwoPCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTwoPCReply) ProtoMessage() {}

func (x *CreateTwoPCReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_twopc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTwoPCReply.ProtoReflect.Descriptor instead.
func (*CreateTwoPCReply) Descriptor() ([]byte, []int) {
	return file_protos_twopc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTwoPCReply) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type TwoPCCommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid         string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	ActualStatus string `protobuf:"bytes,2,opt,name=actualStatus,proto3" json:"actualStatus,omitempty"`
}

func (x *TwoPCCommit) Reset() {
	*x = TwoPCCommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_twopc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoPCCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCCommit) ProtoMessage() {}

func (x *TwoPCCommit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_twopc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCCommit.ProtoReflect.Descriptor instead.
func (*TwoPCCommit) Descriptor() ([]byte, []int) {
	return file_protos_twopc_proto_rawDescGZIP(), []int{2}
}

func (x *TwoPCCommit) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *TwoPCCommit) GetActualStatus() string {
	if x != nil {
		return x.ActualStatus
	}
	return ""
}

var File_protos_twopc_proto protoreflect.FileDescriptor

var file_protos_twopc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x77, 0x6f, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x70, 0x71, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0c, 0x54, 0x77, 0x6f, 0x50, 0x43,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x77, 0x6f,
	0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0x45, 0x0a,
	0x0b, 0x54, 0x77, 0x6f, 0x50, 0x43, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0xdf, 0x01, 0x0a, 0x0c, 0x54, 0x77, 0x6f, 0x50, 0x43, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x32,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x70,
	0x71, 0x72, 0x2e, 0x54, 0x77, 0x6f, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x77, 0x6f,
	0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x18, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x32, 0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x54, 0x77, 0x6f,
	0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x32, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x11, 0x2e, 0x73, 0x70, 0x71, 0x72,
	0x2e, 0x54, 0x77, 0x6f, 0x50, 0x43, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x70, 0x71, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_twopc_proto_rawDescOnce sync.Once
	file_protos_twopc_proto_rawDescData = file_protos_twopc_proto_rawDesc
)

func file_protos_twopc_proto_rawDescGZIP() []byte {
	file_protos_twopc_proto_rawDescOnce.Do(func() {
		file_protos_twopc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_twopc_proto_rawDescData)
	})
	return file_protos_twopc_proto_rawDescData
}

var file_protos_twopc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_twopc_proto_goTypes = []interface{}{
	(*TwoPCRequest)(nil),     // 0: spqr.TwoPCRequest
	(*CreateTwoPCReply)(nil), // 1: spqr.CreateTwoPCReply
	(*TwoPCCommit)(nil),      // 2: spqr.TwoPCCommit
	(*emptypb.Empty)(nil),    // 3: google.protobuf.Empty
}
var file_protos_twopc_proto_depIdxs = []int32{
	0, // 0: spqr.TwoPCService.Create2PhaseCommit:input_type -> spqr.TwoPCRequest
	0, // 1: spqr.TwoPCService.Update2PhaseCommitStatus:input_type -> spqr.TwoPCRequest
	2, // 2: spqr.TwoPCService.Finish2PhaseCommit:input_type -> spqr.TwoPCCommit
	1, // 3: spqr.TwoPCService.Create2PhaseCommit:output_type -> spqr.CreateTwoPCReply
	3, // 4: spqr.TwoPCService.Update2PhaseCommitStatus:output_type -> google.protobuf.Empty
	3, // 5: spqr.TwoPCService.Finish2PhaseCommit:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_twopc_proto_init() }
func file_protos_twopc_proto_init() {
	if File_protos_twopc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_twopc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_twopc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTwoPCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_twopc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoPCCommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_twopc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_twopc_proto_goTypes,
		DependencyIndexes: file_protos_twopc_proto_depIdxs,
		MessageInfos:      file_protos_twopc_proto_msgTypes,
	}.Build()
	File_protos_twopc_proto = out.File
	file_protos_twopc_proto_rawDesc = nil
	file_protos_twopc_proto_goTypes = nil
	file_protos_twopc_proto_depIdxs = nil
}
